name: .NET Linux Publish Pre-Release

on:
  push:
    branches: [ "master", "v*" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Restore dependencies
      run: dotnet restore Pmad.Wiki.sln

    - name: Build
      run: dotnet build --no-restore --configuration Release Pmad.Wiki.sln
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release Pmad.Wiki.sln
      
    - name: Publish NuGet package to GitHub
      run: |
        dotnet nuget add source --username jetelain --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/jetelain/index.json"
        dotnet nuget push **/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s github --skip-duplicate

